DROP TABLE IF EXISTS GATEWAY;

DROP TABLE IF EXISTS DEVICE;

CREATE TABLE GATEWAY (
  UID VARCHAR(250) NOT NULL PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  address VARCHAR(250) NOT NULL
);


CREATE TABLE DEVICE (
  UID INT NOT NULL PRIMARY KEY,
  vendor VARCHAR(250) NOT NULL,
  date_created DATE NOT NULL,
  status INT NOT NULL,
  gateway_ID VARCHAR(250) NOT NULL 
);
